# syntax=docker/dockerfile:1
# Build stage
FROM oven/bun:1-alpine AS build-stage
WORKDIR /app

# Copy package files
COPY package*.json bun.lockb* ./
RUN bun install --frozen-lockfile

# Copy source code
COPY . .

# Accept build arguments for Firebase configuration
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_AUTH_URL
ARG VITE_APP_URL
ARG VITE_CHANNEL_URL
ARG VITE_META_APP_ID
ARG VITE_PUSHER_APP_KEY
ARG VITE_PUSHER_HOST
ARG VITE_CRM_URL
# Set environment variables for build (ARGs become ENVs for the build step)
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_AUTH_URL=$VITE_AUTH_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_CHANNEL_URL=$VITE_CHANNEL_URL
ENV VITE_META_APP_ID=$VITE_META_APP_ID
ENV VITE_PUSHER_APP_KEY=$VITE_PUSHER_APP_KEY
ENV VITE_PUSHER_HOST=$VITE_PUSHER_HOST
ENV VITE_CRM_URL=$VITE_CRM_URL

# Build the application
RUN bun run build

# Production stage: Serve with Nginx
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
