services:
  missionx-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_AUTH_URL=${VITE_AUTH_URL}
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_CHANNEL_URL=${VITE_CHANNEL_URL}
    container_name: missionx-client
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - missionx-network

networks:
  missionx-network:
    driver: bridge
