export const mockTickets = [
  {
    id: "1",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "normal",
    subject: "Product inquiry",
    contactAvatarUrl: "https://github.com/shadcn.png",
    customer: { id: "c1", name: "Sarah Johnson" },
    sentiment: "neutral",
    unreadCount: 2,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Sarah Johnson",
    firstName: "Sarah",
    lastName: "Johnson",
    lastMessage: "Hey! I have a question about your product...",
    timestamp: "2 min ago",
    unread: 2,
    channel: "facebook",
  },
  {
    id: "2",
    workspaceId: "ws-1",
    channelType: "instagram_business",
    status: "pending",
    priority: "normal",
    subject: "Thank you message",
    customer: {
      id: "c2",
      name: "Mike Chen",
    },
    sentiment: "positive",
    unreadCount: 0,
    lastMessageAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Mike Chen",
    firstName: "Mike",
    lastName: "Chen",
    lastMessage: "Thanks for your help!",
    timestamp: "1 hour ago",
    unread: 0,
    channel: "instagram",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
  {
    id: "3",
    workspaceId: "ws-1",
    channelType: "facebook_page",
    status: "open",
    priority: "high",
    subject: "Details request",
    customer: {
      id: "c3",
      name: "Emma Wilson",
    },
    sentiment: "neutral",
    unreadCount: 1,
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Legacy properties
    contactName: "Emma Wilson",
    firstName: "Emma",
    lastName: "Wilson",
    lastMessage: "Can you send me more details?",
    timestamp: "2 hours ago",
    unread: 1,
    channel: "facebook",
  },
];

export const mockMessages = {
  "1": [
    {
      id: "m1",
      sender: "Sarah Johnson",
      text: "Hey! I have a question about your product...",
      time: "10:30 AM",
      isAgent: false,
    },
    {
      id: "m2",
      sender: "Sarah Johnson",
      text: "Is it available in different colors?",
      time: "10:31 AM",
      isAgent: false,
    },
  ],
  "2": [
    {
      id: "m3",
      sender: "Mike Chen",
      text: "Hi, I need help with my order",
      time: "9:15 AM",
      isAgent: false,
    },
    {
      id: "m4",
      sender: "You",
      text: "Of course! What can I help you with?",
      time: "9:16 AM",
      isAgent: true,
    },
    {
      id: "m5",
      sender: "Mike Chen",
      text: "Thanks for your help!",
      time: "9:20 AM",
      isAgent: false,
    },
  ],
  "3": [
    {
      id: "m6",
      sender: "Emma Wilson",
      text: "Can you send me more details?",
      time: "8:45 AM",
      isAgent: false,
    },
  ],
};

export const mockCustomerData = {
  name: "Sarah Johnson",
  avatar: "https://github.com/shadcn.png",
  email: "sarah.johnson@example.com",
  phone: "+1 (555) 123-4567",
  location: "San Francisco, CA",
  joinedDate: "Jan 2024",
  tags: ["VIP", "Returning Customer", "Newsletter"],
  totalOrders: 12,
  totalSpent: "$1,245.00",
};

export const mockOrders = [
  {
    id: "ORD-001",
    date: "Jan 25, 2026",
    amount: "$89.99",
    status: "delivered" as const,
    items: 2,
  },
  {
    id: "ORD-002",
    date: "Jan 20, 2026",
    amount: "$149.99",
    status: "pending" as const,
    items: 1,
  },
  {
    id: "ORD-003",
    date: "Jan 15, 2026",
    amount: "$59.99",
    status: "delivered" as const,
    items: 3,
  },
];

export const mockNotes = [
  {
    id: "n1",
    content: "Customer prefers email communication over phone calls.",
    timestamp: "2 hours ago",
    author: "John Doe",
  },
  {
    id: "n2",
    content: "Interested in bulk order discounts for future purchases.",
    timestamp: "1 day ago",
    author: "Jane Smith",
  },
];
