import type { ReactNode } from "react";
import {
  AtSign,
  Building,
  Calendar,
  Clock,
  DollarSign,
  FileText,
  Globe,
  Hash,
  IdCard,
  Info,
  Key,
  Mail,
  MapPin,
  MessageSquare,
  Phone,
  Star,
  Tag,
  User,
} from "lucide-react";

export const FIELD_ICONS: Record<string, ReactNode> = {
  email: <Mail className="h-4 w-4" />,
  phone: <Phone className="h-4 w-4" />,
  username: <AtSign className="h-4 w-4" />,
  name: <User className="h-4 w-4" />,
  first_name: <User className="h-4 w-4" />,
  last_name: <User className="h-4 w-4" />,
  full_name: <User className="h-4 w-4" />,
  gender: <User className="h-4 w-4" />,
  profile_pic: <User className="h-4 w-4" />,
  profile_pic_url: <User className="h-4 w-4" />,
  locale: <Globe className="h-4 w-4" />,
  language: <Globe className="h-4 w-4" />,
  timezone: <Clock className="h-4 w-4" />,
  location: <MapPin className="h-4 w-4" />,
  address: <MapPin className="h-4 w-4" />,
  city: <MapPin className="h-4 w-4" />,
  country: <MapPin className="h-4 w-4" />,
  state: <MapPin className="h-4 w-4" />,
  zip: <MapPin className="h-4 w-4" />,
  postal_code: <MapPin className="h-4 w-4" />,
  platform: <Globe className="h-4 w-4" />,
  platform_id: <Hash className="h-4 w-4" />,
  app_id: <Key className="h-4 w-4" />,
  id: <IdCard className="h-4 w-4" />,
  source: <Building className="h-4 w-4" />,
  channel: <MessageSquare className="h-4 w-4" />,
  tags: <Tag className="h-4 w-4" />,
  tag: <Tag className="h-4 w-4" />,
  notes: <FileText className="h-4 w-4" />,
  note: <FileText className="h-4 w-4" />,
  assigned_to: <User className="h-4 w-4" />,
  assignee: <User className="h-4 w-4" />,
  lifetime_value: <DollarSign className="h-4 w-4" />,
  ltv: <DollarSign className="h-4 w-4" />,
  value: <DollarSign className="h-4 w-4" />,
  amount: <DollarSign className="h-4 w-4" />,
  price: <DollarSign className="h-4 w-4" />,
  revenue: <DollarSign className="h-4 w-4" />,
  is_active: <Star className="h-4 w-4" />,
  active: <Star className="h-4 w-4" />,
  status: <Info className="h-4 w-4" />,
  is_blocked: <Tag className="h-4 w-4" />,
  blocked: <Tag className="h-4 w-4" />,
  created_at: <Calendar className="h-4 w-4" />,
  created: <Calendar className="h-4 w-4" />,
  updated_at: <Calendar className="h-4 w-4" />,
  updated: <Calendar className="h-4 w-4" />,
  last_seen: <Clock className="h-4 w-4" />,
  last_seen_at: <Clock className="h-4 w-4" />,
  last_interaction: <Clock className="h-4 w-4" />,
  last_interaction_at: <Clock className="h-4 w-4" />,
  date: <Calendar className="h-4 w-4" />,
  age: <Hash className="h-4 w-4" />,
  company: <Building className="h-4 w-4" />,
  organization: <Building className="h-4 w-4" />,
  website: <Globe className="h-4 w-4" />,
  url: <Globe className="h-4 w-4" />,
  link: <Globe className="h-4 w-4" />,
};

export const DEFAULT_FIELD_ICON = <Info className="h-4 w-4" />;
