/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicOAuthCallbackRouteImport } from './routes/_public/OAuthCallback'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivateInboxRouteImport } from './routes/_private/inbox'
import { Route as PrivateChannelsRouteImport } from './routes/_private/channels'
import { Route as PrivateAppsRouteImport } from './routes/_private/apps'
import { Route as PrivateSettingsSlugRouteImport } from './routes/_private/settings.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOAuthCallbackRoute = PublicOAuthCallbackRouteImport.update({
  id: '/OAuthCallback',
  path: '/OAuthCallback',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateInboxRoute = PrivateInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateChannelsRoute = PrivateChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateAppsRoute = PrivateAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsSlugRoute = PrivateSettingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof PrivateAppsRoute
  '/channels': typeof PrivateChannelsRoute
  '/inbox': typeof PrivateInboxRoute
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/OAuthCallback': typeof PublicOAuthCallbackRoute
  '/login': typeof PublicLoginRoute
  '/settings/$slug': typeof PrivateSettingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof PrivateAppsRoute
  '/channels': typeof PrivateChannelsRoute
  '/inbox': typeof PrivateInboxRoute
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/OAuthCallback': typeof PublicOAuthCallbackRoute
  '/login': typeof PublicLoginRoute
  '/settings/$slug': typeof PrivateSettingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/apps': typeof PrivateAppsRoute
  '/_private/channels': typeof PrivateChannelsRoute
  '/_private/inbox': typeof PrivateInboxRoute
  '/_private/settings': typeof PrivateSettingsRouteWithChildren
  '/_public/OAuthCallback': typeof PublicOAuthCallbackRoute
  '/_public/login': typeof PublicLoginRoute
  '/_private/settings/$slug': typeof PrivateSettingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/channels'
    | '/inbox'
    | '/settings'
    | '/OAuthCallback'
    | '/login'
    | '/settings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/channels'
    | '/inbox'
    | '/settings'
    | '/OAuthCallback'
    | '/login'
    | '/settings/$slug'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/apps'
    | '/_private/channels'
    | '/_private/inbox'
    | '/_private/settings'
    | '/_public/OAuthCallback'
    | '/_public/login'
    | '/_private/settings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/OAuthCallback': {
      id: '/_public/OAuthCallback'
      path: '/OAuthCallback'
      fullPath: '/OAuthCallback'
      preLoaderRoute: typeof PublicOAuthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/inbox': {
      id: '/_private/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof PrivateInboxRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/channels': {
      id: '/_private/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof PrivateChannelsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/apps': {
      id: '/_private/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof PrivateAppsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings/$slug': {
      id: '/_private/settings/$slug'
      path: '/$slug'
      fullPath: '/settings/$slug'
      preLoaderRoute: typeof PrivateSettingsSlugRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
  }
}

interface PrivateSettingsRouteChildren {
  PrivateSettingsSlugRoute: typeof PrivateSettingsSlugRoute
}

const PrivateSettingsRouteChildren: PrivateSettingsRouteChildren = {
  PrivateSettingsSlugRoute: PrivateSettingsSlugRoute,
}

const PrivateSettingsRouteWithChildren = PrivateSettingsRoute._addFileChildren(
  PrivateSettingsRouteChildren,
)

interface PrivateRouteChildren {
  PrivateAppsRoute: typeof PrivateAppsRoute
  PrivateChannelsRoute: typeof PrivateChannelsRoute
  PrivateInboxRoute: typeof PrivateInboxRoute
  PrivateSettingsRoute: typeof PrivateSettingsRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAppsRoute: PrivateAppsRoute,
  PrivateChannelsRoute: PrivateChannelsRoute,
  PrivateInboxRoute: PrivateInboxRoute,
  PrivateSettingsRoute: PrivateSettingsRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicOAuthCallbackRoute: typeof PublicOAuthCallbackRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicOAuthCallbackRoute: PublicOAuthCallbackRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
